"""Exercise the preset-all step used by Yocto's rootfs postprocessing."""
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest


FILES = (Path(__file__).resolve().parents[1] / "meta-project" /
         "recipes-core/matrix-console/files")
SYSTEMCTL = os.environ.get("SYSTEMCTL", "systemctl")


@unittest.skipUnless(shutil.which(SYSTEMCTL), "systemctl is required")
class MatrixPresetTest(unittest.TestCase):
    def test_rootfs_presets_keep_tty1_masked_and_enable_tty2(self):
        with tempfile.TemporaryDirectory(prefix="matrix-preset-") as tmp:
            root = Path(tmp)
            units = root / "usr/lib/systemd/system"
            presets = root / "usr/lib/systemd/system-preset"
            config = root / "etc/systemd/system"
            for directory in (units, presets, config):
                directory.mkdir(parents=True)
            (units / "getty@.service").write_text(
                "[Service]\nExecStart=/bin/true\n"
                "[Install]\nWantedBy=getty.target\nDefaultInstance=tty1\n")
            (units / "getty.target").write_text("[Unit]\nDescription=Gettys\n")
            (units / "multi-user.target").write_text("[Unit]\nDescription=Multi-user\n")
            (units / "matrix-console.service").write_text(
                (FILES / "matrix-console.service").read_text()
                .replace("@BINDIR@", "/usr/bin"))
            (config / "getty@tty1.service").symlink_to("/dev/null")

            # Mimic distro defaults plus the preset generated by systemd.bbclass.
            (presets / "90-default.preset").write_text("enable getty@.service\n")
            (presets / "98-matrix-console.preset").write_text(
                "enable matrix-console.service\n")
            (presets / "99-default.preset").write_text("disable *\n")

            def apply_presets(mode):
                return subprocess.run(
                    [SYSTEMCTL, f"--root={root}", f"--preset-mode={mode}", "preset-all"],
                    capture_output=True, text=True,
                    env=dict(os.environ, LC_ALL="C"))

            # Older systemd reports the masked-unit failure but returns success;
            # newer versions (including the CI build) fail the rootfs command.
            broken = apply_presets("enable-only")
            self.assertIn("masked", broken.stderr)
            self.assertIn("Failed to preset", broken.stderr)
            self.assertFalse((config / "getty.target.wants/getty@tty2.service").exists())

            shutil.copyfile(FILES / "00-matrix-console.preset",
                            presets / "00-matrix-console.preset")
            # Check the exact rootfs command, its idempotence, and normal preset-all.
            for mode in ("enable-only", "enable-only", "full"):
                with self.subTest(mode=mode):
                    result = apply_presets(mode)
                    self.assertEqual(result.returncode, 0, result.stderr)
                    self.assertNotIn("Failed to preset", result.stderr)
                    self.assertEqual(os.readlink(config / "getty@tty1.service"), "/dev/null")
                    self.assertEqual(
                        os.readlink(config / "getty.target.wants/getty@tty2.service"),
                        "/usr/lib/systemd/system/getty@.service")
                    self.assertFalse(os.path.lexists(
                        config / "getty.target.wants/getty@tty1.service"))
                    self.assertEqual(
                        os.readlink(config / "multi-user.target.wants/matrix-console.service"),
                        "/usr/lib/systemd/system/matrix-console.service")


if __name__ == "__main__":
    unittest.main()
