name: ci-main

on:
  push:
    branches:
      - main

env:
  ARCHIVE: /var/code/reckless-corp/storage/archive
  KAS_CACHE: /var/code/reckless-corp/storage/kas

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: intel-corei7-64
            artifacts: >-
              core-image-full-cmdline-intel-corei7-64.rootfs.spdx.json
              core-image-full-cmdline-intel-corei7-64.rootfs.wic.zst
              core-image-full-cmdline-intel-corei7-64.rootfs.wic.qcow2
              ovmf*
          - name: uno-q
            artifacts: >-
              core-image-full-cmdline-uno-q.rootfs.qcomflash
              core-image-full-cmdline-uno-q.rootfs.spdx.json

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Kas Build
        run: |
          set -ex

          echo "ANDY ${{ github.run_number }}"

          export DL_DIR=${KAS_CACHE}/downloads
          export SSTATE_DIR=${KAS_CACHE}/sstate-cache
          export KAS_WORK_DIR=`pwd`/.kas-work
          mkdir -p ${KAS_WORK_DIR}/build/conf ${DL_DIR} ${SSTATE_DIR}

          ./kas-container build ${{ matrix.name }}.yml

      - name: Archive
        run: |
          set -ex
          archive="${ARCHIVE}/meta-foundries/${GITHUB_SHA}/${{ matrix.name }}"
          mkdir -p "${archive}"

          cd .kas-work/build/tmp/deploy/images/${{ matrix.name }}
          ls
          tar -czf "${archive}/ostree_repo.tgz" ostree_repo
          cp -rL ${{ matrix.artifacts }} "${archive}/"

  archive:
    needs: build
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Archive
        run: |
          set -ex
          number="${{ github.run_number }}"

          mv ${ARCHIVE}/meta-foundries/${GITHUB_SHA} ${ARCHIVE}/meta-foundries/${number}_${GITHUB_SHA}
